server:
  port: 8888

spring:
  application:
    name: dynamic-tp-zookeeper-demo
  dynamic:
    tp:
      config-type: json # zookeeper支持properties / json 配置
      zookeeper:
        zk-connect-str: 127.0.0.1:2181
        root-node: /configserver/dev
        node: dtp-group
        config-key: dynamic-tp-zookeeper-demo-json


#logging:
#  level:
#    root: DEBUG