server:
  port: 9103

spring:
  application:
    name: dynamic-tp-adapter-grpc-demo
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yml
        extension-configs:
          - dataId: ${spring.application.name}-dtp-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
            group: DEFAULT_GROUP
            refresh: true  # 必须配置，负责自动刷新不生效
        refresh-enabled: true

dynamictp:
  enabled: true
  enabledCollect: true          # 是否开启监控指标采集，默认false
  collectorTypes: logging       # 监控数据采集器类型（logging | micrometer | internal_logging），默认micrometer
  monitorInterval: 5
  platforms:                    # 通知报警平台配置
    - platform: wechat
      urlKey: 3a7500-1287-4bd-a798-c5c3d8b69c  # 替换
      receivers: test1,test2                   # 接受人企微名称
    - platform: ding
      urlKey: f80dad441fcd655438f4a08dcd6a     # 替换
      secret: SECb5441fa6f375d5b9d21           # 替换，非sign模式可以没有此值
      receivers: 15810119805                   # 钉钉账号手机号
    - platform: lark
      urlKey: 0d944ae7-b24a-40                 # 替换
      receivers: test1,test2                   # 接受人飞书名称/openid
  grpcTp:                                      # grpc 线程池配置
    - threadPoolName: grpcTp#9999
      corePoolSize: 100
      maximumPoolSize: 200
      keepAliveTime: 60

grpc:
  server:
    port: 9999
    in-process-name: test

  client:
    cloud-grpc-server:
      address: 'discovery:///dynamic-tp-adapter-grpc-demo'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

# 开启 SpringBoot Actuator Endpoint 暴露出DynamicTp指标接口
# 开启 prometheus 指标采集端点
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'   # 测试使用，线上不要用*，按需开启